apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: demo-voting-app
spec:
  containers:
  - name: db
    image: postgres:9.4
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust