apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: myapp
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-contanier
        image: nginx