apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: MYAPP
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: MYAPP
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      containers:
      - name: nginx-contanier
        image: nginx
        